matrix:
  include:
    - name: CUDA 10.2
      env:
      - CUDA=10.2.89-1
      - CUDA_APT=10-2
      - CUDA_SHORT=10.2
     
      dist: bionic

cache:
  timeout: 1000
  ccache: true
  directories: 
    - $HOME/.hunter
script:
  - ./build.sh
  
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name yashrajsingh1998
      - git config --local user.email yashrajs949@gmail.com
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
    
      
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN

  file: build/test
  
 
