language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true
    - COVERAGE=false
    - UNIT_TESTS=true COMPILER=g++-6     BOOST_VERSION=default ENABLE_MEMCHECK=true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
#       env: UNIT_TESTS=true COMPILER=g++-6     BOOST_VERSION=default ENABLE_MEMCHECK=true
      addons:
       apt:
         packages: 
#            - boost1.67
           - gcc
           - g++-6
           - libboost-all-dev
           #- gcov-4.9
           #- clang-3.7
           #- valgrind
           # Misc
           #- python-yaml
           - lcov
           #- libopencv-dev
         sources: 
           - sourceline: 'ppa:mhier/libboost-latest'
           - llvm-toolchain-precise-3.7 
           - ubuntu-toolchain-r-test
           
         artifacts: true  
    
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - sudo pip install codecov
    
    # Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi
script:
     - ./build.sh

 
# before_deploy:
#       # Set up git user name and tag this commit
#       - git config --local user.name yashrajsingh1998
#       - git config --local user.email yashrajs949@gmail.com
#       - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#       - git tag $TRAVIS_TAG
      
      
# deploy:
#   provider: releases
#   skip_cleanup: true
#   api_key: $GITHUB_TOKEN
#   file: build/test1
  
  
