language: cpp
compiler: gcc
addons:
  apt:
    packages: libboost-all-dev
cache:
  directories: 
    - /build
    - /.mtime_cache
    
before_install:
  - sudo pip install codecov

script:
  - - ruby ../bin/mtime_cache -g mtime_cache_globs.txt -c .mtime_cache/cache.json
  - ./build.sh
#   - /mtime_cache_demo


