matrix:
  include:
    - name: CUDA 10.2
      env:
      - CUDA=10.2.89-1
      - CUDA_APT=10-2
      - CUDA_SHORT=10.2
     
      dist: bionic

cache:
  timeout: 1000
  ccache: true
  directories: 
    - $HOME/.hunter
script:
  - ./build.sh
  
 
